---
- name: "Listen for newly added ServiceAccount resources"
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: ServiceAccount
        namespace: test-cm
  rules:
    - name: Notify
      condition: event.type == "ADDED"
      action:
        run_job_template:
          name: "Show SA token"
          organization: "Infrastructure"
          post_events: true
          var_root: resource
             
