---
- name: "Listen for newly added ServiceAccount resources"
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: ServiceAccount
        namespace: test-cm
  rules:
    - name: Set facts
      condition: event.type == "ADDED"
      action:
        set_fact:
          event_data: {{ event }}
    - name: Notify
      condition: event.type == "ADDED"
      action:
        run_job_template:
          name: "Show SA token"
          organization: "Infrastructure"
          post_events: true
          var_root: resource
          job_args:
            extra_vars:
              namespace: "{{ event_data }}"
              
            
             
